# env
env: 'SoccerTwos'
model: ${model_maddpg}
work_id: 1
work_id_ev: 2
# train
# num_train_steps: 300000 # 100010
num_train_steps: 200000
num_exploration_steps: 4000
start_training_steps: 0
min_eps: 0.1
seed: 1
replay_buffer_capacity: ${num_train_steps}
# eval
eval_frequency: 20000
num_eval_steps: 10000
# eval_frequency: 20000
# num_eval_steps: 125000
# misc
log_frequency_step: 4000
log_save_tb: true
device: cuda
# global params
batch_size: 16
num_agents: 16

model_maddpg:
  class: maddpg.MADDPG
  name: maddpg
  
  params:
    obs_shape: ??? # to be specified later
    num_actions: ??? # to be specified later
    num_actions_branch: ??? # to be specified later
    device: ${device}
    actor_lr: 0.0001
    critic_lr: 0.001
    critic_tau: 0.01
    gamma: 0.99
    num_agents: ${num_agents}
    critic_target_update_frequency: 100
    max_grad_norm: ${max_grad_norm}
    replay_buffer_capacity: ${replay_buffer_capacity}
    batch_size: ${batch_size}
    max_grad_norm: 0.5
    eval_eps: 0.05




# hydra configuration
hydra:
#  name: ${env}
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${hydra.job.override_dirname}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${agent.name}_${experiment}
    subdir: ${hydra.job.num}
